landing/urls.py
__copyright__ = """

    Copyright 2017 Irdeto BV

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""
__license__ = "Apache 2.0"

from django.conf.urls import url, include
from rest_framework import routers

from landing.views import *
from . import views

router = routers.DefaultRouter()
router.register(r'tenants', TenantViewSet)
router.register(r'surveys', SurveyViewSet)
router.register(r'survey_results', SurveyResultsViewSet)
router.register(r'attack_goals', AttackGoalViewSet, base_name='attack_goals')
router.register(r'attack_graphson', AttackTreeGraphson, base_name='attack_graphson')

app_name = 'landing'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r"^accounts/profile/$", views.profile, name='profile'),
    url(r"^accounts/profile/dashboard/$", Dashboard.as_view(), name='dashboard'),
    url(r"^accounts/profile/attack_goals/$", AttackGoals.as_view(), name='attack_goals'),
    url(r'^api/', include(router.urls))]

portal/urls.py
from rest_framework.documentation import include_docs_urls

__copyright__ = """

    Copyright 2017 Irdeto BV

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""
__license__ = "Apache 2.0"

"""portal URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^docs/', include_docs_urls(title='Threat-Buster API'))
]

landing/models.py
__copyright__ = """

    Copyright 2017 Irdeto BV

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""
__license__ = "Apache 2.0"

from django.contrib.auth.models import User, Group
from django.db import models


# Tenant represents the organization using the service
class Tenant(models.Model):
    name = models.CharField(max_length=1024)
    active = models.BooleanField(default=True)
    users = models.ManyToManyField(User)
    group = models.ForeignKey(Group, blank=True, null=True)

    class Meta:
        verbose_name = "tenant"
        verbose_name_plural = "tenants"

        permissions = (
            ('view_tenant', 'View tenant'),
        )

    def __str__(self):
        return self.name


class Survey(models.Model):
    title = models.TextField(max_length=256)

    def __str__(self):
        return self.title


class Category(models.Model):
    category = models.TextField(max_length=255)
    order = models.PositiveIntegerField(default=0, db_index=True)

    def __str__(self):
        return self.category

    class Meta:
        abstract = True
        verbose_name = "category"
        verbose_name_plural = "categories"
        ordering = ['order']


class ParentCategory(Category):
    def category_count(self):
        return self.childcategory_set.count()

    def category_list(self):
        return ", ".join(str(value.category) for value in self.childcategory_set.all())


class ChildCategory(Category):
    parent_category = models.ForeignKey(ParentCategory)


class Question(models.Model):
    question = models.TextField(max_length=4096)
    order = models.PositiveIntegerField(default=0, db_index=True)
    survey = models.ForeignKey(Survey)
    category = models.ForeignKey(ChildCategory)

    def __str__(self):
        return self.question

    class Meta:
        ordering = ['order']


class SurveyResults(models.Model):
    date = models.DateField(auto_now=True)
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    survey = models.ForeignKey(Survey)

    def __str__(self):
        return "Results for {} on {}".format(self.tenant, self.date)


class SurveyResult(models.Model):
    question = models.ForeignKey(Question)
    answer = models.BooleanField(blank=False)
    survey_results = models.ForeignKey(SurveyResults)

landing/views.py
import json

from django.utils.decorators import method_decorator
from neomodel import db
from rest_framework import viewsets, filters
from rest_framework.mixins import ListModelMixin
from rest_framework.response import Response

from landing.filters import TenantFilter, TenantPermission, UpdatableObjectPermission, AttackGoalFilter
from landing.graph_models import AttackGoal
from landing.models import Survey, Tenant, SurveyResults
from landing.serializers import SurveySerializer, TenantSerializer, SurveyResultsSerializer, AttackGoalSerializer

__copyright__ = """

    Copyright 2017 Irdeto BV

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""
__license__ = "Apache 2.0"

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView


def index(request):
    return render(request, 'landing/index.html')


@login_required
def profile(request):
    user_tenants = request.user.tenant_set.all()
    context = {
        'user_tenants': user_tenants
    }
    return render(request, 'landing/profile.html')


@method_decorator(login_required, name='dispatch')
class Dashboard(TemplateView):
    template_name = "landing/profile_dashboard.html"

    def get_context_data(self, **kwargs):
        xdata = ["Apple", "Apricot", "Avocado", "Banana", "Boysenberries", "Blueberries", "Dates", "Grapefruit", "Kiwi",
                 "Lemon"]
        ydata = [52, 48, 160, 94, 75, 71, 490, 82, 46, 17]
        chartdata = {'x': xdata, 'y': ydata}
        charttype = "pieChart"
        chartcontainer = 'piechart_container'
        data = {
            'charttype': charttype,
            'chartdata': chartdata,
            'chartcontainer': chartcontainer,
            'extra': {
                'x_is_date': False,
                'x_axis_format': '',
                'tag_script_js': True,
                'jquery_on_ready': False,
            }
        }
        return data


@method_decorator(login_required, name='dispatch')
class AttackGoals(TemplateView):
    template_name = "landing/attack_goals.html"


class SurveyViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Survey.objects.all()
    serializer_class = SurveySerializer


class TenantViewSet(viewsets.ModelViewSet):
    queryset = Tenant.objects.all()
    serializer_class = TenantSerializer

    filter_backends = (filters.DjangoObjectPermissionsFilter,)
    permission_classes = (UpdatableObjectPermission,)


class SurveyResultsViewSet(viewsets.ModelViewSet):
    queryset = SurveyResults.objects.all()
    serializer_class = SurveyResultsSerializer

    filter_backends = (TenantFilter,)
    permission_classes = (TenantPermission,)


class AttackGoalViewSet(viewsets.GenericViewSet, ListModelMixin):
    serializer_class = AttackGoalSerializer
    filter_backends = (AttackGoalFilter,)

    def get_queryset(self):
        return AttackGoal.nodes

    def retrieve(self, request, pk=None):
        node = AttackGoal.nodes.get(pk)
        serializer = AttackGoalSerializer(node)
        return Response(serializer.data)


class AttackTreeGraphson(viewsets.ViewSet):
    def list(self, request):
        relations, nodesMeta = db.cypher_query("MATCH (a:AttackGoal)-[b*]->(c) return a,b,c", None)

        outputNodes = []
        outputEdges = []

        outputNodes.append({
            "id": len(outputNodes),
            "uid": relations[0][0].id,
            "caption": relations[0][0].properties['title'],
            "type": list(relations[0][0].labels)[0],
            "root": True
        })

        ids = {relations[0][0].id: len(outputNodes) - 1}

        for relation in relations:
            outputNodes.append({
                "id": len(outputNodes),
                "uid": relation[2].id,
                "caption": relation[2].properties['title'],
                "type": list(relation[2].labels)[0]
            })
            ids[relation[2].id] = len(outputNodes) - 1

            for relationship in relation[1]:
                outputEdges.append({
                    "source": ids[relationship.start],
                    "target": ids[relationship.end],
                    "type": relationship.type

                })

        return Response({'nodes': outputNodes, 'edges': outputEdges})

landing/templates/landing/attack_goals.html
{% extends "base.html" %}
{% load staticfiles %}


{% block extra_head %}

    <script type="text/javascript" src="{% static 'd3/d3.js' %}"></script>
    <link href="{% static 'landing/css/threat-buster.css' %}" rel="stylesheet"/>
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="{% url 'landing:profile' %}">Profiles</a></li>
        <li class="active"><a href="#">Attack Goals</a></li>
    </ol>
{% endblock %}

{% block content %}
    <h1>Attack Goals - D3 Direct</h1>

    <div id="graph"/>

    <script>
        var width = 500, height = 200;
        // force layout setup
        var force = d3.layout.force()
            .charge(-200).linkDistance(120).size([width, height]);

        // setup svg div
        var svg = d3.select("#graph").append("svg")
            .attr("width", "100%").attr("height", "100%")
            .attr("pointer-events", "all");

        // load graph (nodes,links) json from /graph endpoint
        d3.json("/api/attack_graphson/", function (error, graph) {
            if (error) return;

            force.nodes(graph.nodes).links(graph.edges).start();

            // render relationships as lines
            var link = svg.selectAll(".edge")
                .data(graph.edges).enter()
                .append("g").attr("class", "edge_group")
                .append("line").attr("class", "edge");

            // render nodes as circles, css-class from label
            var node = svg.selectAll(".node")
                .data(graph.nodes).enter()
                .append("g").attr("class", "node_group")
                .append("circle")
                .attr("class", function (d) {
                    return "node_" + d.type
                })
                .attr("r", 10)
                .call(force.drag);

            // html title attribute for title node-attribute
            node.append("title")
                .text(function (d) {
                    return d.caption;
                })

            var linkText = svg.selectAll(".edge_group")
                .append("text")
                .attr("class", "link-label")
                .attr("fill", "Black")
                .attr("dy", ".35em")
                .attr("text-anchor", "middle")
                .text(function (d) {
                    return d.caption;
                });

            var nodeText = svg.selectAll(".node_group")
                .append("text")
                .attr("class", "link-label")
                .attr("fill", "Black")
                .attr("dy", ".35em")
                .attr("text-anchor", "middle")
                .text(function (d) {
                    return d.caption;
                });

            // force feed algo ticks for coordinate computation
            force.on("tick", function () {
                link.attr("x1", function (d) {
                    return d.source.x;
                })
                    .attr("y1", function (d) {
                        return d.source.y;
                    })
                    .attr("x2", function (d) {
                        return d.target.x;
                    })
                    .attr("y2", function (d) {
                        return d.target.y;
                    });

                node.attr("cx", function (d) {
                    return d.x;
                })
                    .attr("cy", function (d) {
                        return d.y;
                    });

                linkText
                    .attr("x", function (d) {
                        return ((d.source.x + d.target.x) / 2);
                    })
                    .attr("y", function (d) {
                        return ((d.source.y + d.target.y) / 2);
                    });

                nodeText
                    .attr("x", function (d) {
                        return d.x;
                    })
                    .attr("y", function (d) {
                        return d.y;
                    });
            });
        });
    </script>


{% endblock %}

landing/templates/landing/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

    <!-- Full Width Image Header -->
    <header class="header-image">
        <div class="headline">
            <div class="container">
                <h1>Threat Buster</h1>
                <h2>TAGLINE</h2>
            </div>
        </div>
    </header>

    <!-- Page Content -->
    <div class="container">

        <hr class="featurette-divider">

        <!-- First Featurette -->
        <div class="featurette" id="feature1">
            <img class="featurette-image img-circle img-responsive pull-right"
                 src="{% static 'landing/i/Totally_Socks_Donkey.png' %}">
            <h2 class="featurette-heading">FIRST Feature
                <span class="text-muted">Sub Tag Line</span>
            </h2>
            <p class="lead"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut pharetra urna. Donec
                scelerisque, dolor quis luctus tincidunt, ex orci dignissim elit, non tempor augue velit eget ante.
                Mauris eleifend placerat libero id pretium. Donec orci erat, rhoncus nec lorem a, pellentesque dapibus
                ligula. Ut congue mauris lacinia, condimentum nisl nec, dictum libero. Morbi in odio a lacus bibendum
                sagittis. Donec id eleifend ligula. Donec fringilla luctus lacus, hendrerit rutrum neque luctus quis. Ut
                eros risus, sollicitudin nec felis id, pharetra egestas ante. Etiam imperdiet porta leo, at blandit
                tortor placerat vel. Etiam rutrum convallis est, eu pulvinar leo feugiat sed. Nulla magna felis,
                volutpat ut nunc quis, placerat accumsan felis. Vestibulum ante ipsum primis in faucibus orci luctus et
                ultrices posuere cubilia Curae; </p>
        </div>

        <hr class="featurette-divider">

        <!-- Second Featurette -->
        <div class="featurette" id="feature2">
            <img class="featurette-image img-circle img-responsive pull-left" src="{% static 'landing/i/Lock.png' %}">
            <h2 class="featurette-heading">Second Feature
                <span class="text-muted">Sub Tag Line</span>
            </h2>
            <p class="lead"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ut pharetra urna. Donec
                scelerisque, dolor quis luctus tincidunt, ex orci dignissim elit, non tempor augue velit eget ante.
                Mauris eleifend placerat libero id pretium. Donec orci erat, rhoncus nec lorem a, pellentesque dapibus
                ligula. Ut congue mauris lacinia, condimentum nisl nec, dictum libero. Morbi in odio a lacus bibendum
                sagittis. Donec id eleifend ligula. Donec fringilla luctus lacus, hendrerit rutrum neque luctus quis. Ut
                eros risus, sollicitudin nec felis id, pharetra egestas ante. Etiam imperdiet porta leo, at blandit
                tortor placerat vel. Etiam rutrum convallis est, eu pulvinar leo feugiat sed. Nulla magna felis,
                volutpat ut nunc quis, placerat accumsan felis. Vestibulum ante ipsum primis in faucibus orci luctus et
                ultrices posuere cubilia Curae; </p>
        </div>

        <hr class="featurette-divider">

        <!-- Third Featurette -->
        <div class="featurette" id="plans">
            <img class="featurette-image img-circle img-responsive pull-right" src="{% static 'landing/i/Light.png' %}">
            <h2 class="featurette-heading">Sign up
                <span class="text-muted"> </span>
            </h2>
            <p class="lead">ThreatBuster is currently in invite only beta. <a href="{% url 'account_signup' %}">Sign
                up here to register your interest</a></p>
        </div>

        <hr class="featurette-divider">

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Irdeto 2017</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

{% endblock content %}

landing/templates/landing/profile.html
{% extends "base.html" %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li class="active"><a href="#">Profiles</a></li>
    </ol>
{% endblock %}

{% block content %}
    <h1>Profile</h1>
    {% load account %}
    <p> Hello {% user_display user %}</p>

    <div class="row">
        <div class="col-md-2">

            <ul>
                <li><a href="{% url 'account_change_password' %}">Change Password</a></li>
                <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
                <li><a href="{% url 'landing:attack_goals' %}">Attack Goals</a></li>
                <li><a href="{% url 'landing:dashboard' %}">Reports</a></li>
                {% if user.is_superuser %}
                    <li><a href="{% url 'admin:index' %}">Administration</a></li>
                {% endif %}

            </ul>
        </div>
        <div class="col-md-10">
            <div class="panel panel-primary">
                <div class="panel-heading">Welcome</div>
                <div class="panel-body">
                    <p>Welcome Text</p>
                </div>
            </div>
        </div>


{% endblock %}

landing/templates/landing/profile_dashboard.html
{% extends "base.html" %}
{% load nvd3_tags %}

{% block extra_head %}
    {% include_chart_jscss %}
    {% load_chart charttype chartdata chartcontainer extra %}
{%  endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="{% url 'landing:profile' %}">Profiles</a></li>
        <li class="active"><a href="#">Dashboard</a></li>
    </ol>
{% endblock %}

{% block content %}
    <h1>Dashboard</h1>
    {% include_container chartcontainer 400 600 %}

{%  endblock %}

landing/templates/landing/tenant_form.html
{% extends "base.html" %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="/">Home</a></li>
        <li><a href="{% url 'landing:profile' %}">Profiles</a></li>
        <li><a href="{% url 'landing:sites' %}">Sites</a></li>
        <li><a href="{% url 'landing:site-details' object.id %}">Sites {{ object.name }}</a></li>
        <li class="active"><a href="#">Edit</a></li>
    </ol>
{% endblock %}

{% block content %}
    <h1>Site {{ object.name }} </h1>
    <form action="{% url 'landing:tenant-edit' object.id %}" method="post">
        <div class="form-group">
            {% csrf_token %}
            <div class="form-inline">
            {% for field in form %}
                <fieldset class="form-group">
                    {{ field.label_tag }} {{ field }}
                </fieldset>
            {% endfor %}
            </div>

            <h2>Endpoints</h2>
            {{ endpoint_form.management_form }}
            <div class="row">
            <div class="col-md-2">Hostname</div>
            <div class="col-md-2">Active</div></div>

            {% for form in endpoint_form %}
                <div class="form-inline row">
                    <div class="col-md-2">{{ form.id }}
                    {{  form.endpoint_hostname }}</div>
                    <div class="col-md-2">{{ form.active }}</div>
                </div>
            {% endfor %}
            <input type="submit" value="Submit" class="btn btn-primary"/>
        </div>
    </form>
{% endblock %}