landing/urls.py
__copyright__ = """

    Copyright 2017 Irdeto BV

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""
__license__ = "Apache 2.0"

from django.conf.urls import url, include
from rest_framework import routers

from landing.views import *
from . import views

router = routers.DefaultRouter()
router.register(r'tenants', TenantViewSet)
router.register(r'surveys', SurveyViewSet)
router.register(r'survey_results', SurveyResultsViewSet)
router.register(r'attack_goals', AttackGoalViewSet, base_name='attack_goals')
router.register(r'attack_graphson', AttackTreeGraphson, base_name='attack_graphson')

app_name = 'landing'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r"^accounts/profile/$", views.profile, name='profile'),
    url(r"^accounts/profile/dashboard/$", Dashboard.as_view(), name='dashboard'),
    url(r"^accounts/profile/attack_goals/$", AttackGoals.as_view(), name='attack_goals'),
    url(r'^api/', include(router.urls))]

portal/urls.py
from rest_framework.documentation import include_docs_urls

__copyright__ = """

    Copyright 2017 Irdeto BV

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""
__license__ = "Apache 2.0"

"""portal URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('landing.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^docs/', include_docs_urls(title='Threat-Buster API'))
]

landing/models.py
__copyright__ = """

    Copyright 2017 Irdeto BV

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""
__license__ = "Apache 2.0"

from django.contrib.auth.models import User, Group
from django.db import models


# Tenant represents the organization using the service
class Tenant(models.Model):
    name = models.CharField(max_length=1024)
    active = models.BooleanField(default=True)
    users = models.ManyToManyField(User)
    group = models.ForeignKey(Group, blank=True, null=True)

    class Meta:
        verbose_name = "tenant"
        verbose_name_plural = "tenants"

        permissions = (
            ('view_tenant', 'View tenant'),
        )

    def __str__(self):
        return self.name


class Survey(models.Model):
    title = models.TextField(max_length=256)

    def __str__(self):
        return self.title


class Category(models.Model):
    category = models.TextField(max_length=255)
    order = models.PositiveIntegerField(default=0, db_index=True)

    def __str__(self):
        return self.category

    class Meta:
        abstract = True
        verbose_name = "category"
        verbose_name_plural = "categories"
        ordering = ['order']


class ParentCategory(Category):
    def category_count(self):
        return self.childcategory_set.count()

    def category_list(self):
        return ", ".join(str(value.category) for value in self.childcategory_set.all())


class ChildCategory(Category):
    parent_category = models.ForeignKey(ParentCategory)


class Question(models.Model):
    question = models.TextField(max_length=4096)
    order = models.PositiveIntegerField(default=0, db_index=True)
    survey = models.ForeignKey(Survey)
    category = models.ForeignKey(ChildCategory)

    def __str__(self):
        return self.question

    class Meta:
        ordering = ['order']


class SurveyResults(models.Model):
    date = models.DateField(auto_now=True)
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    survey = models.ForeignKey(Survey)

    def __str__(self):
        return "Results for {} on {}".format(self.tenant, self.date)


class SurveyResult(models.Model):
    question = models.ForeignKey(Question)
    answer = models.BooleanField(blank=False)
    survey_results = models.ForeignKey(SurveyResults)

landing/views.py
import json

from django.utils.decorators import method_decorator
from neomodel import db
from rest_framework import viewsets, filters
from rest_framework.mixins import ListModelMixin
from rest_framework.response import Response

from landing.filters import TenantFilter, TenantPermission, UpdatableObjectPermission, AttackGoalFilter
from landing.graph_models import AttackGoal
from landing.models import Survey, Tenant, SurveyResults
from landing.serializers import SurveySerializer, TenantSerializer, SurveyResultsSerializer, AttackGoalSerializer

__copyright__ = """

    Copyright 2017 Irdeto BV

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""
__license__ = "Apache 2.0"

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView


def index(request):
    return render(request, 'landing/index.html')


@login_required
def profile(request):
    user_tenants = request.user.tenant_set.all()
    context = {
        'user_tenants': user_tenants
    }
    return render(request, 'landing/profile.html')


@method_decorator(login_required, name='dispatch')
class Dashboard(TemplateView):
    template_name = "landing/profile_dashboard.html"

    def get_context_data(self, **kwargs):
        xdata = ["Apple", "Apricot", "Avocado", "Banana", "Boysenberries", "Blueberries", "Dates", "Grapefruit", "Kiwi",
                 "Lemon"]
        ydata = [52, 48, 160, 94, 75, 71, 490, 82, 46, 17]
        chartdata = {'x': xdata, 'y': ydata}
        charttype = "pieChart"
        chartcontainer = 'piechart_container'
        data = {
            'charttype': charttype,
            'chartdata': chartdata,
            'chartcontainer': chartcontainer,
            'extra': {
                'x_is_date': False,
                'x_axis_format': '',
                'tag_script_js': True,
                'jquery_on_ready': False,
            }
        }
        return data


@method_decorator(login_required, name='dispatch')
class AttackGoals(TemplateView):
    template_name = "landing/attack_goals.html"


class SurveyViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Survey.objects.all()
    serializer_class = SurveySerializer


class TenantViewSet(viewsets.ModelViewSet):
    queryset = Tenant.objects.all()
    serializer_class = TenantSerializer

    filter_backends = (filters.DjangoObjectPermissionsFilter,)
    permission_classes = (UpdatableObjectPermission,)


class SurveyResultsViewSet(viewsets.ModelViewSet):
    queryset = SurveyResults.objects.all()
    serializer_class = SurveyResultsSerializer

    filter_backends = (TenantFilter,)
    permission_classes = (TenantPermission,)


class AttackGoalViewSet(viewsets.GenericViewSet, ListModelMixin):
    serializer_class = AttackGoalSerializer
    filter_backends = (AttackGoalFilter,)

    def get_queryset(self):
        return AttackGoal.nodes

    def retrieve(self, request, pk=None):
        node = AttackGoal.nodes.get(pk)
        serializer = AttackGoalSerializer(node)
        return Response(serializer.data)


class AttackTreeGraphson(viewsets.ViewSet):
    def list(self, request):
        relations, nodesMeta = db.cypher_query("MATCH (a:AttackGoal)-[b*]->(c) return a,b,c", None)

        outputNodes = []
        outputEdges = []

        outputNodes.append({
            "id": len(outputNodes),
            "uid": relations[0][0].id,
            "caption": relations[0][0].properties['title'],
            "type": list(relations[0][0].labels)[0],
            "root": True
        })

        ids = {relations[0][0].id: len(outputNodes) - 1}

        for relation in relations:
            outputNodes.append({
                "id": len(outputNodes),
                "uid": relation[2].id,
                "caption": relation[2].properties['title'],
                "type": list(relation[2].labels)[0]
            })
            ids[relation[2].id] = len(outputNodes) - 1

            for relationship in relation[1]:
                outputEdges.append({
                    "source": ids[relationship.start],
                    "target": ids[relationship.end],
                    "type": relationship.type

                })

        return Response({'nodes': outputNodes, 'edges': outputEdges})

landing/templates/base.html
{% load staticfiles %}
{% load analytical %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% analytical_head_top %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block head_title %}Threat Buster{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'landing/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'landing/css/one-page-wonder.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% block extra_head %}{% endblock %}
    {% analytical_head_bottom %}

</head>
<body>
{% analytical_body_top %}
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="{% url 'landing:index' %}">
                <img src="{% static 'landing/i/irdeto_logo.svg' %}"/>
            </a>

        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'landing:index' %}#plans">Sign up</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                </li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'landing:profile' %}">Profile</a></li>
                    <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
                {% else %}
                    <li><a href="{% url 'account_login' %}">Sign In</a></li>
                    <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

{% block body %}
    {% if messages %}
        <div class="alert-success alert-dismissable">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}

    {% block breadcrumb %}{% endblock %}

    <div class="container">
        {% block content %}{% endblock content %}
        {% block main_content %}{% endblock %}
    </div>

{% endblock body %}
{% block extra_body %}
{% endblock %}

<!-- jQuery -->
<script src="{% static 'landing/js/jquery.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'landing/js/bootstrap.min.js' %}"></script>

{% analytical_body_bottom %}
</body>

</html>